### ISSUE TITLE
Как насчет использования git-book а лучше сразу sharelatex?

### ISSUE THREAD

**Issue by bookvik** [rigidus/onlisp#6]
https://www.gitbook.com

https://www.sharelatex.com/

**Comment by amadev** [comment]
Казалось бы org-mode самый подходящий для такой книги )
И пример уже: https://github.com/rigidus/onlisp/blob/master/Chapter%2022.%20Nondeterminism.org

**Comment by bookvik** [comment]
Все это придется в итоге переверстывать после перевода.

**Comment by rigidus** [comment]
Хороший пример, да
